# Generated by Django 4.1.7 on 2023-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_services', '0002_rename_serv_otherservs_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Фото'),
        ),
    ]
