# Generated by Django 4.1.7 on 2023-02-22 19:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_services', '0005_singleservice1_text_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_phone', models.CharField(max_length=20, verbose_name='Первый номер')),
                ('tel_nums_newacc', models.CharField(max_length=15, verbose_name='Номер телефона для новых аккаунтов')),
                ('tel_nums_support', models.CharField(max_length=15, verbose_name='Служба поддержки')),
                ('first_email', models.EmailField(max_length=254, verbose_name='почта')),
                ('second_email', models.EmailField(max_length=254, verbose_name='почта2')),
                ('adress', models.CharField(max_length=255, verbose_name='Адресс')),
                ('youtube', models.CharField(max_length=155, verbose_name='Ссылка на youtube')),
                ('twitter', models.CharField(max_length=155, verbose_name='Ссылка на twitter')),
                ('facebook', models.CharField(max_length=155, verbose_name='Ссылка на facebook')),
                ('linkedin', models.CharField(max_length=155, verbose_name='Ссылка на linkedin')),
                ('google', models.CharField(max_length=155, verbose_name='Ссылка на google')),
            ],
            options={
                'verbose_name_plural': 'Single_service2 Контакты',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название плана')),
                ('curs', models.CharField(blank=True, max_length=10, null=True, verbose_name='Курс оплаты')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cymma oплаты ')),
                ('category', models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория')),
                ('color', models.CharField(blank=True, max_length=15, null=True, verbose_name='цвет')),
            ],
            options={
                'verbose_name_plural': 'page Service3 План',
            },
        ),
        migrations.CreateModel(
            name='SingleService2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.CharField(blank=True, max_length=155, null=True, verbose_name='Что включает план')),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='single_services.plan', verbose_name='План')),
            ],
            options={
                'verbose_name_plural': 'Что включает',
            },
        ),
    ]
