# Generated by Django 4.1.7 on 2023-02-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_services', '0006_contacts_plan_singleservice2_includes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleservice2',
            options={'verbose_name_plural': 'Single_service 1'},
        ),
    ]
