# Generated by Django 4.1.7 on 2023-02-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_services', '0007_alter_singleservice2_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleservice2',
            options={'verbose_name_plural': 'Single_service 2'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='single_services.singleservice2'),
            preserve_default=False,
        ),
    ]
