# Generated by Django 4.1.7 on 2023-02-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_services', '0008_alter_singleservice2_options_contacts_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Single_Service2 План'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='first_email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='head_phone',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='second_email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='tel_nums_newacc',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='tel_nums_support',
        ),
    ]
