# Generated by Django 4.1.7 on 2023-02-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1word1', models.CharField(max_length=30, verbose_name='первое слово слайда 1')),
                ('s1word2', models.CharField(max_length=30, verbose_name='третье слово слайда 1')),
                ('s2word1', models.CharField(max_length=30, verbose_name='первое слово слайда 2')),
                ('s2word2', models.CharField(max_length=30, verbose_name='третье слово слайда 2')),
                ('s3word1', models.CharField(max_length=30, verbose_name='первое слово слайда 3')),
                ('s3word2', models.CharField(max_length=30, verbose_name='третье слово слайда 3')),
            ],
            options={
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
