# Generated by Django 4.1.7 on 2023-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0003_slides_s1word3_slides_s2word3_slides_s3word3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(help_text='наша компания одна из лучших', verbose_name='о нас')),
                ('sentences1', models.TextField(verbose_name='Предложения')),
                ('feachered', models.TextField(verbose_name='Подчеркнутое предложение')),
                ('sentences2', models.TextField(verbose_name='Предложения')),
            ],
        ),
        migrations.AddField(
            model_name='slides',
            name='s1word4',
            field=models.CharField(default=1, max_length=30, verbose_name='четвертое слово слайда 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slides',
            name='s1word5',
            field=models.CharField(default=1, max_length=30, verbose_name='пятое слово слайда 1'),
            preserve_default=False,
        ),
    ]
