# Generated by Django 4.1.7 on 2023-02-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0004_block1_slides_s1word4_slides_s1word5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block1',
            options={'verbose_name_plural': 'О нас'},
        ),
    ]
