# Generated by Django 4.1.7 on 2023-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0005_alter_block1_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block1',
            name='about',
            field=models.TextField(help_text='например: наша компания одна из лучших', verbose_name='о нас'),
        ),
    ]
