# Generated by Django 4.1.7 on 2023-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0006_alter_block1_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryportfolio',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='categoryportfolio',
            name='about',
            field=models.TextField(default=1, verbose_name='O категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryportfolio',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryportfolio',
            name='slug',
            field=models.SlugField(default=1, max_length=30, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
