# Generated by Django 4.1.7 on 2023-02-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0008_alter_services_options_categoryportfolio_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название портфолио'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=1, max_length=30, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='фото'),
        ),
    ]
