# Generated by Django 4.1.7 on 2023-02-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0009_alter_portfolio_options_portfolio_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рекламы')),
                ('desc', models.TextField(verbose_name='Описание рекламы')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisement', verbose_name='фото')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotcreative.advertisement', verbose_name='реклаma')),
            ],
            options={
                'verbose_name_plural': 'Фото рекламы',
            },
        ),
    ]
