# Generated by Django 4.1.7 on 2023-02-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0010_advertisement_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name_plural': 'Реклама'},
        ),
        migrations.AlterModelOptions(
            name='block1',
            options={'verbose_name_plural': 'block1 О нас'},
        ),
        migrations.AlterModelOptions(
            name='categoryportfolio',
            options={'verbose_name_plural': 'block2 Категории'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'block6 Фото рекламы'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'block4 Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'block3 Услуги'},
        ),
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name_plural': 'block0 Слайды'},
        ),
    ]
