# Generated by Django 4.1.7 on 2023-02-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0011_alter_advertisement_options_alter_block1_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name_plural': 'block6 Реклама'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Фото рекламы'},
        ),
    ]
