# Generated by Django 4.1.7 on 2023-02-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0012_alter_advertisement_options_alter_images_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
    ]
