# Generated by Django 4.1.7 on 2023-02-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0013_remove_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name_on_image',
            field=models.CharField(default=1, max_length=155, verbose_name='Название на фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='text_on_image',
            field=models.TextField(default=1, verbose_name='Текст на фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisement', verbose_name='фото'),
        ),
    ]
