# Generated by Django 4.1.7 on 2023-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0014_advertisement_name_on_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='name_on_image',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='text_on_image',
        ),
        migrations.AddField(
            model_name='images',
            name='name_on_image',
            field=models.CharField(default=1, max_length=155, verbose_name='Название на фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='text_on_image',
            field=models.TextField(default=1, verbose_name='Текст на фото'),
            preserve_default=False,
        ),
    ]
