# Generated by Django 4.1.7 on 2023-02-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0015_advert_remove_advertisement_name_on_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
