# Generated by Django 4.1.7 on 2023-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0016_images_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
