# Generated by Django 4.1.7 on 2023-02-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0017_delete_advert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Block8 Отзывы'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фотот автора'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='job',
            field=models.CharField(default=1, max_length=155, verbose_name='Должность автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default=1, max_length=155, verbose_name='Имя автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.TextField(default=1, verbose_name='Tekct'),
            preserve_default=False,
        ),
    ]
