# Generated by Django 4.1.7 on 2023-02-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0018_alter_reviews_options_reviews_image_reviews_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Block10 Контакты'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='adress',
            field=models.CharField(default=1, max_length=255, verbose_name='Адресс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='first_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='second_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='почта2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='tel_nums_newacc',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер телефона для новых аккаунтов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='tel_nums_support',
            field=models.CharField(default=1, max_length=15, verbose_name='Служба поддержки'),
            preserve_default=False,
        ),
    ]
