# Generated by Django 4.1.7 on 2023-02-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0019_delete_plan_alter_contacts_options_contacts_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='facebook',
            field=models.SlugField(default=1, verbose_name='Ссылка на facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='google',
            field=models.SlugField(default=1, verbose_name='Ссылка на google'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='linkedin',
            field=models.SlugField(default=1, verbose_name='Ссылка на linkedin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='twitter',
            field=models.SlugField(default=1, verbose_name='Ссылка на twitter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='youtube',
            field=models.SlugField(default=1, verbose_name='Ссылка на youtube'),
            preserve_default=False,
        ),
    ]
