# Generated by Django 4.1.7 on 2023-02-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0021_alter_contacts_facebook_alter_contacts_google_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('theme1', models.CharField(max_length=255, verbose_name='Тема текста 1')),
                ('text1', models.TextField(verbose_name='Текст 1')),
                ('theme2', models.CharField(max_length=255, verbose_name='Тема текста 2')),
                ('text2', models.TextField(verbose_name='Текст 2')),
                ('theme3', models.CharField(max_length=255, verbose_name='Тема текста 3')),
                ('text3', models.TextField(verbose_name='Текст 3')),
            ],
            options={
                'verbose_name_plural': 'О нас страница',
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='head_phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Первый номер'),
            preserve_default=False,
        ),
    ]
