# Generated by Django 4.1.7 on 2023-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0022_about_contacts_head_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('about', models.TextField(verbose_name='O категории')),
                ('foto', models.ImageField(null=True, upload_to='foto/', verbose_name='фото')),
            ],
            options={
                'verbose_name_plural': 'Service2 page',
            },
        ),
    ]
