# Generated by Django 4.1.7 on 2023-02-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0024_service3'),
    ]

    operations = [
        migrations.AddField(
            model_name='service3',
            name='plan2',
            field=models.CharField(default=1, max_length=50, verbose_name='Название плана 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service3',
            name='plan3',
            field=models.CharField(default=1, max_length=50, verbose_name='Название плана 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service3',
            name='plan_1',
            field=models.CharField(default=1, max_length=50, verbose_name='Название плана 1'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Plan1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curs', models.CharField(blank=True, max_length=10, null=True, verbose_name='Курс оплаты')),
                ('summ', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cymma oплаты оплаты')),
                ('cent', models.CharField(blank=True, max_length=2, null=True, verbose_name='cent')),
                ('include', models.CharField(blank=True, max_length=155, null=True, verbose_name='Что включает план')),
                ('serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotcreative.service3', verbose_name='План')),
            ],
            options={
                'verbose_name_plural': 'План 1',
            },
        ),
    ]
