# Generated by Django 4.1.7 on 2023-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0026_remove_service3_plan2_remove_service3_plan3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan3',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название плана'),
        ),
    ]
