# Generated by Django 4.1.7 on 2023-02-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0027_alter_plan3_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan1',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название плана'),
        ),
        migrations.AlterField(
            model_name='plan2',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название плана'),
        ),
    ]
