# Generated by Django 4.1.7 on 2023-02-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0032_alter_plan_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Includes',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
