# Generated by Django 4.1.7 on 2023-02-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0033_delete_includes_delete_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название плана')),
                ('curs', models.CharField(blank=True, max_length=10, null=True, verbose_name='Курс оплаты')),
                ('summ', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cymma oплаты оплаты')),
                ('cent', models.CharField(blank=True, max_length=2, null=True, verbose_name='cent')),
            ],
            options={
                'verbose_name_plural': 'page Service3 План',
            },
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.CharField(blank=True, max_length=155, null=True, verbose_name='Что включает план')),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotcreative.plan', verbose_name='План')),
            ],
            options={
                'verbose_name_plural': 'Что включает',
            },
        ),
    ]
