# Generated by Django 4.1.7 on 2023-02-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0034_plan_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория'),
        ),
    ]
