# Generated by Django 4.1.7 on 2023-02-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0035_plan_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
                ('desc', models.TextField(verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name_plural': 'page Service 5',
            },
        ),
        migrations.CreateModel(
            name='IncludesServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.CharField(blank=True, max_length=155, null=True, verbose_name='Что включает план')),
                ('servs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotcreative.service5', verbose_name='План')),
            ],
            options={
                'verbose_name_plural': 'Что включает услуга',
            },
        ),
    ]
