# Generated by Django 4.1.7 on 2023-02-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0036_service5_includesserv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='includes',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='includesserv',
            name='servs',
        ),
        migrations.DeleteModel(
            name='Service2',
        ),
        migrations.DeleteModel(
            name='Service3',
        ),
        migrations.DeleteModel(
            name='Includes',
        ),
        migrations.DeleteModel(
            name='IncludesServ',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Service5',
        ),
    ]
