# Generated by Django 4.1.7 on 2023-03-01 22:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotcreative', '0037_remove_includes_plans_remove_includesserv_servs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('recent', 'recent'), ('others', 'others')], max_length=30, verbose_name='Тег')),
                ('date', models.DateField(verbose_name='Дата')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
