# Generated by Django 4.1.7 on 2023-02-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('about', models.TextField(verbose_name='O категории')),
                ('foto', models.ImageField(null=True, upload_to='foto/', verbose_name='фото')),
                ('slug', models.SlugField(max_length=30, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'block2 Категории',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название плана')),
                ('curs', models.CharField(blank=True, max_length=10, null=True, verbose_name='Курс оплаты')),
                ('summ', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cymma oплаты оплаты')),
                ('cent', models.CharField(blank=True, max_length=2, null=True, verbose_name='cent')),
                ('category', models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'page Service3 План',
            },
        ),
        migrations.CreateModel(
            name='Service2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('about', models.TextField(verbose_name='O категории')),
                ('foto', models.ImageField(null=True, upload_to='foto/', verbose_name='фото')),
            ],
            options={
                'verbose_name_plural': 'Service2 page',
            },
        ),
        migrations.CreateModel(
            name='Service3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('about', models.TextField(verbose_name='O категории')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/', verbose_name='фото')),
            ],
            options={
                'verbose_name_plural': 'Service3 page',
            },
        ),
        migrations.CreateModel(
            name='Service5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
                ('desc', models.TextField(verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name_plural': 'page Service 5',
            },
        ),
        migrations.CreateModel(
            name='IncludesServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.CharField(blank=True, max_length=155, null=True, verbose_name='Что включает план')),
                ('servs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service5', verbose_name='План')),
            ],
            options={
                'verbose_name_plural': 'Что включает услуга',
            },
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.CharField(blank=True, max_length=155, null=True, verbose_name='Что включает план')),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.plan', verbose_name='План')),
            ],
            options={
                'verbose_name_plural': 'Что включает',
            },
        ),
    ]
