# Generated by Django 4.1.7 on 2023-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='cent',
        ),
        migrations.AlterField(
            model_name='plan',
            name='summ',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cymma oплаты оплаты'),
            preserve_default=False,
        ),
    ]
