# Generated by Django 4.1.7 on 2023-02-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_plan_cent_alter_plan_summ'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='summ',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cymma oплаты '),
        ),
    ]
