# Generated by Django 4.1.7 on 2023-02-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_plan_color_alter_plan_summ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'page Single_Service3 План'},
        ),
    ]
