# Generated by Django 4.1.7 on 2023-02-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_plan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'page Service3 План'},
        ),
    ]
